<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    'General module settings'                                          => 'Основные настройки модуля',
    'Images settings'                                                  => 'Настройки изображений',
    '*unknown*'                                                        => '*неизвестно*',
    '- no matter -'                                                    => '- не важен -',
    '-no matter-'                                                      => '- не важно -',
    '--choose--'                                                       => '--выберите--',
    '0.4'                                                              => '0.4',
    'Id'                                                               => 'Id',
    'http://yupe.ru'                                                   => 'http://yupe.ru',
    'team@yupe.ru'                                                     => 'team@yupe.ru',
    'yupe team'                                                        => 'yupe team',
    'Author'                                                           => 'Автор',
    'Alias'                                                            => 'Алиас',
    'Visual Editor'                                                    => 'Визуальный редактор',
    'You inserting translation for {lang} language'                    => 'Вы добавляете перевод на {lang} язык!',
    'Data for SEO'                                                     => 'Данные для поисковой оптимизации',
    'Date'                                                             => 'Дата',
    'Updated at'                                                       => 'Дата изменения',
    'Created at'                                                       => 'Дата создания',
    'Directory "{dir}" is not accessible for write! {link}'            => 'Директория "{dir}" не доступна для записи! {link}',
    'You must be an authorized user for view this page!'               => 'Для просмотра этой страницы Вам необходимо авторизоваться!',
    'Add translation for {lang} language'                              => 'Добавить перевод на {lang} язык',
    'Create'                                                           => 'Добавление',
    'Access only for authorized'                                       => 'Доступ только для авторизованных',
    'Delete'                                                           => 'Удалить',
    'Do you really want to delete selected elements?'                  => 'Вы уверены, что хотите удалить выбранные элементы?',
    'Title'                                                            => 'Заголовок',
    'Bad characters in {attribute} field'                              => 'Запрещенные символы в поле {attribute}',
    'Requested page was not found!'                                    => 'Запрошенная страница не найдена!',
    'Change settings'                                                  => 'Изменить настройки',
    'Image'                                                            => 'Фото',
    'Uploading files catalog (relatively {path})'                      => 'Каталог для загрузки файлов (относительно {path})',
    'Category'                                                         => 'Категория',
    'Keywords (SEO)'                                                   => 'Ключевые слова (SEO)',
    'RSS records'                                                      => 'Количество записей в RSS',
    'Content'                                                          => 'Контент',
    'Short text'                                                       => 'Короткий текст',
    'Maximum size (in bytes)'                                          => 'Максимальный размер (в байтах)',
    'Minimum size (in bytes)'                                          => 'Минимальный размер (в байтах)',
    'On moderation'                                                    => 'На модерации',
    'Bad raquest. Please don\'t use similar requests anymore!'         => 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы!',
    'Staff'                                                            => 'Сотрудники',
    'staff'                                                            => 'сотрудники',
    'Staff list'                                                       => 'Список сотрудников',
    'Worker add'                                                       => 'Добавить сотрудника',
    'First name'                                                       => 'Имя',
    'Last name'                                                        => 'Фамилия',
    'Patronymic'                                                       => 'Отчество',
    'Fields with'                                                      => 'Поля, отмеченные',
    'Menu items order'                                                 => 'Порядок следования в меню',
    'Public URL'                                                       => 'Публичный урл',
    'Accepted extensions (separated by comma)'                         => 'Разрешенные расширения (перечислите через запятую)',
    'Edit'                                                             => 'Редактирование',
    'Edit translation in to {lang} language'                           => 'Редактировать перевод на {lang} язык',
    'Link'                                                             => 'Ссылка',
    'Status'                                                           => 'Статус',
    'Management'                                                       => 'Управление',
    'Draft'                                                            => 'Черновик',
    'Language'                                                         => 'Язык',
    'Language was not found!'                                          => 'Язык не найден!',
    'yes'                                                              => 'да',
    'create'                                                           => 'добавление',
    'no'                                                               => 'нет',
    'are required'                                                     => 'обязательны.',
    'management'                                                       => 'управление',
    'Data'                                                             => 'Данные',
    'Add'                                                              => 'Добавить',
    'Save worker and continue'                                         => 'Обновить сотрудника и продолжить',
    'Save worker and close'                                            => 'Обновить сотрудника и закрыть',
    'Add worker and continue'                                          => 'Добавить сотрудника и продолжить',
    'Add worker and close'                                             => 'Добавить сотрудника и закрыть',

];
